require('~/webrtc')
let peer;


function sendWebsocket() {
    var id = document.getElementById("session-id").value;
    var url = "ws://localhost:8080/api/session/" + id + "/navigator";
    var ws = new WebSocket(url);

    ws.onopen = function() {
      peer = new prepareNewConnection(true);
      peer.ontrack = evt => {
        console.log('-- peer.ontrack()');
      };
            // ICE Candidateを収集したときのイベント
      peer.onicecandidate = evt => {
        if (evt.candidate) {
            console.log(evt.candidate);
        } else {
            console.log('empty ice event');
        }
      };
      let sendObject = {
        "kind": "request_sdp",
        "payload": "",
      };
      ws.send(JSON.stringify(sendObject));
    };

    ws.onmessage = function(evt) {
        console.log(evt.data);
        const sdp = JSON.parse(evt.data);
        if(sdp.kind === "sdp") {
          const peer = prepareNewConnection();
            peer.ontrack = (ev) => {
                console.log(ev);
            }
            peer.onicecandidate = evt => {
              if (evt.candidate) {
                  console.log(evt.candidate);
              } else {
                const sdp = peer.localDescription;
                const sendObject = {
                  "kind": "sdp",
                  "payload": "<SDP generated by Navigator>"
                }
              }
            };
        }

    };

    ws.onclose = function() {
        console.log("closed");
    };

    ws.onerror = function(evt) {
        alert("error");
    };
}
