
function sendWebsocket()
{ 
    var id = document.getElementById("session-id").value;
    var url = "ws://localhost:8080/api/session/" + id + "/navigator"
    var ws = new WebSocket("wss://echo.websocket.org")

    ws.onopen = function()
    {
        let sendObject = {
            "kind": "sdp",
            "payload": "<SDP generated by Navigator>"
        }
        ws.send(JSON.stringify(sendObject));
    }

    ws.onmessage = function(evt)
    {
        console.log(evt.data);
    }

    ws.onclose = function()
    {
        console.log("closed")
    }

    ws.onerror = function(evt)
    {
        alert("error")
    }
}