/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package club.itsp.elang.agmob.workspace

import io.ktor.application.call
import io.ktor.http.ContentType
import io.ktor.response.respondText
import io.ktor.routing.get
import io.ktor.routing.post
import io.ktor.routing.routing
import io.ktor.server.engine.embeddedServer
import io.ktor.server.netty.Netty

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)

    embeddedServer(Netty, 8080) {
        routing {
            get("/api/session") {
                call.respondText("FIXME: Create a session and return id", ContentType.Text.Plain)
            }
            post("/api/session") {
                call.respondText("FIXME: Create a session and return id", ContentType.Text.Plain)
            }
        }
    }.start(wait = true)
}
